services:

  medilabo-doc-api:
    image: medilabo-doc-api
    build:
      context: ./medilabo-doc-api
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/notes_patient
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - medilabo-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=notes_patient
    volumes:
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongo_data:/data/db/
    networks:
      - medilabo-network
    healthcheck:
      test: [ "CMD-SHELL", "mongosh --eval 'db.runCommand({ ping: 1 })'" ]
      interval: 10s
      timeout: 5s
      retries: 5


  medilabo-patient-api:
    image: medilabo-patient-api
    build:
      context: ./medilabo-patient-api
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/medilabo
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - medilabo-network

  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: medilabo
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/medilabo-patient-api_db_root_password
    secrets:
      - medilabo-patient-api_db_root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - medilabo-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
      interval: 10s
      timeout: 5s
      retries: 5


  medilabo-reporting-api:
    image: medilabo-reporting-api
    build:
      context: ./medilabo-reporting-api
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    networks:
      - medilabo-network


  medilabo-gateway:
    image: medilabo-gateway
    build:
      context: ./medilabo-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - medilabo-doc-api
      - medilabo-patient-api
      - medilabo-reporting-api
    networks:
      - medilabo-network


  medilabo-site:
    image: medilabo-site
    build:
      context: ./medilabo-site
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - medilabo-gateway
    networks:
      - medilabo-network


networks:
  medilabo-network:

volumes:
  mysql_data:
  mongo_data:

secrets:
  medilabo-patient-api_db_root_password:
    file: secrets/medilabo-patient-api_db_root_password.txt